name: Publish container image

on:
  push:
    branches:
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ secrets.DOCKER_REPOSITORY }}
          tags: latest
          containerfiles: |
            ./Containerfile

      - uses: redhat-actions/push-to-registry@v2
        with:
          registry: docker.io
          image: ${{ secrets.DOCKER_REPOSITORY }}
          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
